/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/academic-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** years */
        get: operations["getacademicYears"];
        put?: never;
        /** storeYear */
        post: operations["postacademicYears"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** deleteYear */
        delete: operations["deleteacademicYearsYear"];
        options?: never;
        head?: never;
        /** updateYear */
        patch: operations["patchacademicYearsYear"];
        trace?: never;
    };
    "/api/v1/academic-years/{year}/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: operations["getacademicYearsYearClasses"];
        put?: never;
        /** store */
        post: operations["postacademicYearsYearClasses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}/classes/import/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** commit */
        post: operations["postacademicYearsYearClassesImportCommit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}/classes/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** preview */
        post: operations["postacademicYearsYearClassesImportPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}/classes/{schoolClass}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: operations["deleteacademicYearsYearClassesSchoolClass"];
        options?: never;
        head?: never;
        /** update */
        patch: operations["patchacademicYearsYearClassesSchoolClass"];
        trace?: never;
    };
    "/api/v1/academic-years/{year}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** closeYear */
        post: operations["postacademicYearsYearClose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** openYear */
        post: operations["postacademicYearsYearOpen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** reopenYear */
        post: operations["postacademicYearsYearReopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/{year}/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** semesters */
        get: operations["getacademicYearsYearSemesters"];
        put?: never;
        /** storeSemester */
        post: operations["postacademicYearsYearSemesters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** changePassword */
        post: operations["postauthChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** login */
        post: operations["postauthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** logout */
        post: operations["postauthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** catalog */
        get: operations["getcatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: operations["getcontext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context/current-semester": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** update */
        put: operations["putcontextCurrentSemester"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** grades */
        get: operations["getgrades"];
        put?: never;
        /** storeGrade */
        post: operations["postgrades"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grades/{grade}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** deleteGrade */
        delete: operations["deletegradesGrade"];
        options?: never;
        head?: never;
        /** updateGrade */
        patch: operations["patchgradesGrade"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** health */
        get: operations["gethealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** currentUser */
        get: operations["getme"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/school-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: operations["getschoolSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** update */
        patch: operations["patchschoolSettings"];
        trace?: never;
    };
    "/api/v1/semesters/{semester}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** showSemester */
        get: operations["getsemestersSemester"];
        put?: never;
        post?: never;
        /** deleteSemester */
        delete: operations["deletesemestersSemester"];
        options?: never;
        head?: never;
        /** updateSemester */
        patch: operations["patchsemestersSemester"];
        trace?: never;
    };
    "/api/v1/semesters/{semester}/class-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: operations["getsemestersSemesterClassSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/class-settings/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** copy */
        post: operations["postsemestersSemesterClassSettingsCopy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/class-settings/{schoolClass}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** put */
        put: operations["putsemestersSemesterClassSettingsSchoolClass"];
        post?: never;
        /** destroy */
        delete: operations["deletesemestersSemesterClassSettingsSchoolClass"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/class-settings/{schoolClass}/migrate-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** migrateRoom */
        post: operations["postsemestersSemesterClassSettingsSchoolClassMigrateRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** closeSemester */
        post: operations["postsemestersSemesterClose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** openSemester */
        post: operations["postsemestersSemesterOpen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** reopenSemester */
        post: operations["postsemestersSemesterReopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/schedule-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: operations["getsemestersSemesterScheduleTemplate"];
        /** put */
        put: operations["putsemestersSemesterScheduleTemplate"];
        post?: never;
        /** destroy */
        delete: operations["deletesemestersSemesterScheduleTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/schedule-template/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** copy */
        post: operations["postsemestersSemesterScheduleTemplateCopy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: operations["getsemestersSemesterTeachingTasks"];
        put?: never;
        /** store */
        post: operations["postsemestersSemesterTeachingTasks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** confirm */
        post: operations["postsemestersSemesterTeachingTasksConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** copy */
        post: operations["postsemestersSemesterTeachingTasksCopy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: operations["deletesemestersSemesterTeachingTasksTask"];
        options?: never;
        head?: never;
        /** update */
        patch: operations["patchsemestersSemesterTeachingTasksTask"];
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/{task}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** deactivate */
        post: operations["postsemestersSemesterTeachingTasksTaskDeactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/{task}/migrate-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** migrateRoom */
        post: operations["postsemestersSemesterTeachingTasksTaskMigrateRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/{task}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** restore */
        post: operations["postsemestersSemesterTeachingTasksTaskRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/teaching-tasks/{task}/unconfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** unconfirm */
        post: operations["postsemestersSemesterTeachingTasksTaskUnconfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: operations["getsemestersSemesterTimetable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable/completeness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** completeness */
        get: operations["getsemestersSemesterTimetableCompleteness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** store */
        post: operations["postsemestersSemesterTimetableEntries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable/entries/{entry}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: operations["deletesemestersSemesterTimetableEntriesEntry"];
        options?: never;
        head?: never;
        /** update */
        patch: operations["patchsemestersSemesterTimetableEntriesEntry"];
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable/entries/{entry}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** lock */
        put: operations["putsemestersSemesterTimetableEntriesEntryLock"];
        post?: never;
        /** unlock */
        delete: operations["deletesemestersSemesterTimetableEntriesEntryLock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** export */
        get: operations["getsemestersSemesterTimetableExportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semesters/{semester}/timetable/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** validation */
        get: operations["getsemestersSemesterTimetableValidation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** courses */
        get: operations["getcourses"];
        put?: never;
        /** storeCourse */
        post: operations["postcourses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** deleteCourse */
        delete: operations["deletecoursesCourse"];
        options?: never;
        head?: never;
        /** updateCourse */
        patch: operations["patchcoursesCourse"];
        trace?: never;
    };
    "/api/v1/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** teachers */
        get: operations["getteachers"];
        put?: never;
        /** storeTeacher */
        post: operations["postteachers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/{teacher}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** deleteTeacher */
        delete: operations["deleteteachersTeacher"];
        options?: never;
        head?: never;
        /** updateTeacher */
        patch: operations["patchteachersTeacher"];
        trace?: never;
    };
    "/api/v1/teachers/{teacher}/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** teacherCourses */
        put: operations["putteachersTeacherCourses"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: operations["getusers"];
        put?: never;
        /** store */
        post: operations["postusers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** update */
        patch: operations["patchusersUser"];
        trace?: never;
    };
    "/api/v1/users/{user}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** resetPassword */
        post: operations["postusersUserResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** rooms */
        get: operations["getrooms"];
        put?: never;
        /** storeRoom */
        post: operations["postrooms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{room}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** deleteRoom */
        delete: operations["deleteroomsRoom"];
        options?: never;
        head?: never;
        /** updateRoom */
        patch: operations["patchroomsRoom"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 各操作的字段由对应业务端点校验；客户端生成的 paths 类型保留端点与并发头约束。 */
        WritePayload: {
            [key: string]: unknown;
        };
        Envelope: {
            data: unknown;
            meta?: {
                [key: string]: unknown;
            };
        };
        Problem: {
            message: string;
            code: string;
            request_id: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description 成功 */
        Success: {
            headers: {
                /** @description 当前聚合版本；可编辑读取必须在后续写入中原样作为 If-Match。 */
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 已创建 */
        Created: {
            headers: {
                /** @description 创建后的当前聚合版本。 */
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 结构化业务或验证错误 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
        IfMatch: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getacademicYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYears: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deleteacademicYearsYear: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchacademicYearsYear: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getacademicYearsYearClasses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearClasses: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearClassesImportCommit: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearClassesImportPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deleteacademicYearsYearClassesSchoolClass: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
                schoolClass: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchacademicYearsYearClassesSchoolClass: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
                schoolClass: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearClose: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearOpen: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearReopen: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getacademicYearsYearSemesters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postacademicYearsYearSemesters: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postauthChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postauthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postauthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getcatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getcontext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    putcontextCurrentSemester: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getgrades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postgrades: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletegradesGrade: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                grade: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchgradesGrade: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                grade: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    gethealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getschoolSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchschoolSettings: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletesemestersSemester: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchsemestersSemester: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterClassSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterClassSettingsCopy: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    putsemestersSemesterClassSettingsSchoolClass: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                schoolClass: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletesemestersSemesterClassSettingsSchoolClass: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                schoolClass: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterClassSettingsSchoolClassMigrateRoom: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                schoolClass: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterClose: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterOpen: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterReopen: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterScheduleTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    putsemestersSemesterScheduleTemplate: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletesemestersSemesterScheduleTemplate: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterScheduleTemplateCopy: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterTeachingTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasks: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasksConfirm: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasksCopy: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletesemestersSemesterTeachingTasksTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                task: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchsemestersSemesterTeachingTasksTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                task: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasksTaskDeactivate: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                task: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasksTaskMigrateRoom: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                task: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasksTaskRestore: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                task: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTeachingTasksTaskUnconfirm: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                task: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterTimetable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterTimetableCompleteness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postsemestersSemesterTimetableEntries: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletesemestersSemesterTimetableEntriesEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                entry: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchsemestersSemesterTimetableEntriesEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                entry: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    putsemestersSemesterTimetableEntriesEntryLock: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                entry: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletesemestersSemesterTimetableEntriesEntryLock: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                semester: number;
                entry: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterTimetableExportCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 带 UTF-8 BOM 的安全 CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getsemestersSemesterTimetableValidation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getcourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postcourses: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deletecoursesCourse: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                course: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchcoursesCourse: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                course: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getteachers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postteachers: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deleteteachersTeacher: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                teacher: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchteachersTeacher: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                teacher: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    putteachersTeacherCourses: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                teacher: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getusers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postusers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchusersUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postusersUserResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getrooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    postrooms: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            201: components["responses"]["Created"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    deleteroomsRoom: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                room: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    patchroomsRoom: {
        parameters: {
            query?: never;
            header: {
                /** @description 使用同一次可编辑资源读取响应携带的强 ETag；全局格式为 catalog-N，学期格式为 semester-ID-timetable-N-catalog-N。 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                room: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WritePayload"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
}
